const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data');
const OUTPUT_FILE = path.join(DATA_DIR, 'odds_data.js');

// Mappings
const teamMapping = {
    // Premier League
    "Man United": "Manchester United",
    "Man City": "Manchester City",
    "Nott'm Forest": "Nottingham Forest",
    "Wolves": "Wolverhampton",
    "Sheffield United": "Sheffield Utd",
    "Luton": "Luton Town",
    "Leeds": "Leeds United",
    "Leicester": "Leicester City",
    "Newcastle": "Newcastle United",
    "Norwich": "Norwich City",
    "Spurs": "Tottenham",
    "Tottenham": "Tottenham",
    "West Ham": "West Ham United",
    "Brighton": "Brighton & Hove Albion",
    "West Brom": "West Bromwich Albion",

    // La Liga (Spain)
    "Ath Bilbao": "Athletic Club",
    "Ath Madrid": "Atletico Madrid",
    "Barcelona": "Barcelona",
    "Betis": "Real Betis",
    "Celta": "Celta Vigo",
    "Espanol": "Espanyol",
    "Real Madrid": "Real Madrid",
    "Sevilla": "Sevilla",
    "Sociedad": "Real Sociedad",
    "Valencia": "Valencia",
    "Valladolid": "Real Valladolid",
    "Villarreal": "Villarreal",
    "Girona": "Girona",
    "Alaves": "Alaves",
    "Las Palmas": "Las Palmas",
    "Leganes": "Leganes",
    "Mallorca": "Mallorca",
    "Osasuna": "Osasuna",
    "Rayo Vallecano": "Rayo Vallecano",
    "Vallecano": "Rayo Vallecano",
    "Getafe": "Getafe",

    // Ligue 1 (France)
    "Paris SG": "Paris Saint-Germain",
    "Marseille": "Marseille",
    "Lyon": "Lyon",
    "Monaco": "Monaco",
    "Lille": "Lille",
    "Nice": "Nice",
    "Rennes": "Rennes",
    "Lens": "Lens",
    "Strasbourg": "Strasbourg",
    "Nantes": "Nantes",
    "Reims": "Reims",
    "Montpellier": "Montpellier",
    "Toulouse": "Toulouse",
    "Brest": "Brest",
    "Le Havre": "Le Havre",
    "Auxerre": "Auxerre",
    "Angers": "Angers",
    "St Etienne": "Saint-Etienne"
};

function normalizeTeamName(name) {
    if (!name) return "";
    const trimmed = name.trim();
    return teamMapping[trimmed] || trimmed;
}

function build() {
    console.log("Building odds data...");

    const files = ['E0.csv', 'F1.csv', 'SP1.csv'];
    let allOdds = {};
    let totalMatches = 0;

    files.forEach(filename => {
        const filePath = path.join(DATA_DIR, filename);
        if (!fs.existsSync(filePath)) {
            console.log(`Skipping ${filename} (not found)`);
            return;
        }

        console.log(`Processing ${filename}...`);
        const content = fs.readFileSync(filePath, 'utf8');
        const rows = content.split('\n');

        if (rows.length < 2) return;

        const headers = rows[0].split(',');

        // Find columns dynamically
        const homeIdx = headers.findIndex(h => h.trim() === 'HomeTeam');
        const awayIdx = headers.findIndex(h => h.trim() === 'AwayTeam');
        const dateIdx = headers.findIndex(h => h.trim() === 'Date');

        // Odds columns (Bet365 usually)
        const hOddsIdx = headers.findIndex(h => h.trim() === 'B365H' || h.trim() === 'AvgH');
        const dOddsIdx = headers.findIndex(h => h.trim() === 'B365D' || h.trim() === 'AvgD');
        const aOddsIdx = headers.findIndex(h => h.trim() === 'B365A' || h.trim() === 'AvgA');

        if (homeIdx === -1 || awayIdx === -1) {
            return;
        }

        // Parse rows
        for (let i = 1; i < rows.length; i++) {
            const row = rows[i].split(',');
            if (row.length < 5) continue;

            const home = normalizeTeamName(row[homeIdx]);
            const away = normalizeTeamName(row[awayIdx]);

            if (!home || !away) continue;

            const key = `${home} vs ${away}`;

            // Only add if we have odds
            if (row[hOddsIdx] && row[dOddsIdx] && row[aOddsIdx]) {
                allOdds[key] = {
                    home: parseFloat(row[hOddsIdx]),
                    draw: parseFloat(row[dOddsIdx]),
                    away: parseFloat(row[aOddsIdx]),
                    date: row[dateIdx]
                };
                totalMatches++;
            }
        }
    });

    const jsContent = `// Auto-generated by build_data.js
// Contains historical odds for ${totalMatches} matches
window.HISTORICAL_ODDS = ${JSON.stringify(allOdds, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, jsContent);
    console.log(`✅ Success! Processed ${totalMatches} matches.`);
    console.log(`Saved to: ${OUTPUT_FILE}`);
}

build();
