$ErrorActionPreference = "Stop"

$dataDir = Join-Path $PSScriptRoot "data"
$outputFile = Join-Path $PSScriptRoot "odds_data.js"

Write-Host "Building odds data from CSVs in $dataDir..."

$allOdds = @{}
$count = 0

# Get all CSV files
$files = Get-ChildItem -Path $dataDir -Filter "*.csv"

foreach ($file in $files) {
    Write-Host "Processing $($file.Name)..."
    
    $content = Get-Content -Path $file.FullName
    if ($content.Count -lt 2) { continue }
    
    $headers = $content[0] -split ","
    
    # Find indices
    $homeIdx = $headers.IndexOf("HomeTeam")
    $awayIdx = $headers.IndexOf("AwayTeam")
    $dateIdx = $headers.IndexOf("Date")
    
    # Odds indices (try B365 first, then Avg)
    $hOddsIdx = $headers.IndexOf("B365H")
    if ($hOddsIdx -eq -1) { $hOddsIdx = $headers.IndexOf("AvgH") }
    
    $dOddsIdx = $headers.IndexOf("B365D")
    if ($dOddsIdx -eq -1) { $dOddsIdx = $headers.IndexOf("AvgD") }
    
    $aOddsIdx = $headers.IndexOf("B365A")
    if ($aOddsIdx -eq -1) { $aOddsIdx = $headers.IndexOf("AvgA") }
    
    if ($homeIdx -eq -1 -or $awayIdx -eq -1) { continue }

    # Process rows
    for ($i = 1; $i -lt $content.Count; $i++) {
        $row = $content[$i] -split ","
        if ($row.Count -lt 5) { continue }
        
        $homeTeam = $row[$homeIdx].Trim()
        $awayTeam = $row[$awayIdx].Trim()
        
        # Simple Mapping (Add more as needed)
        $mapping = @{
            "Man United"       = "Manchester United";
            "Man City"         = "Manchester City";
            "Nott'm Forest"    = "Nottingham Forest";
            "Wolves"           = "Wolverhampton";
            "Sheffield United" = "Sheffield Utd";
            "Luton"            = "Luton Town";
            "Leeds"            = "Leeds United";
            "Leicester"        = "Leicester City";
            "Newcastle"        = "Newcastle United";
            "Norwich"          = "Norwich City";
            "Spurs"            = "Tottenham";
            "West Ham"         = "West Ham United";
            "Brighton"         = "Brighton & Hove Albion";
            "Ath Bilbao"       = "Athletic Club";
            "Ath Madrid"       = "Atletico Madrid";
            "Betis"            = "Real Betis";
            "Celta"            = "Celta Vigo";
            "Espanol"          = "Espanyol";
            "Sociedad"         = "Real Sociedad";
            "Valladolid"       = "Real Valladolid";
            "Inter"            = "Inter";
            "Milan"            = "AC Milan";
            "Paris SG"         = "Paris Saint-Germain";
            "St Etienne"       = "Saint-Etienne";
            "Bayern Munich"    = "Bayern Munich";
            "Dortmund"         = "Borussia Dortmund";
            "Leverkusen"       = "Bayer Leverkusen";
            "M'gladbach"       = "Borussia Monchengladbach";
            "Frankfurt"        = "Eintracht Frankfurt"
        }
        
        if ($mapping.ContainsKey($homeTeam)) { $homeTeam = $mapping[$homeTeam] }
        if ($mapping.ContainsKey($awayTeam)) { $awayTeam = $mapping[$awayTeam] }
        
        $key = "$homeTeam vs $awayTeam"
        
        if ($hOddsIdx -ne -1 -and $row[$hOddsIdx] -and $row[$dOddsIdx] -and $row[$aOddsIdx]) {
            $oddsObj = @{
                home = $row[$hOddsIdx]
                draw = $row[$dOddsIdx]
                away = $row[$aOddsIdx]
                date = $row[$dateIdx]
            }
            $allOdds[$key] = $oddsObj
            $count++
        }
    }
}

# Convert to JSON
$json = $allOdds | ConvertTo-Json -Depth 2 -Compress

# Write JS file
$jsContent = "// Auto-generated by build_odds.ps1`nwindow.HISTORICAL_ODDS = $json;"
Set-Content -Path $outputFile -Value $jsContent

Write-Host "✅ Success! Processed $count matches."
Write-Host "Saved to $outputFile"
