const fs = require('fs');
const path = require('path');

// Configuration
const DATA_DIR = path.join(__dirname, 'data');
const OUTPUT_FILE = path.join(__dirname, 'odds_data.js');

// Team Name Mapping (CSV Name -> API Name)
const teamMapping = {
    // Premier League
    "Man United": "Manchester United",
    "Man City": "Manchester City",
    "Nott'm Forest": "Nottingham Forest",
    "Wolves": "Wolverhampton",
    "Sheffield United": "Sheffield Utd",
    "Luton": "Luton Town",
    "Leeds": "Leeds United",
    "Leicester": "Leicester City",
    "Newcastle": "Newcastle United",
    "Norwich": "Norwich City",
    "Spurs": "Tottenham",
    "Tottenham": "Tottenham",
    "West Ham": "West Ham United",
    "Brighton": "Brighton & Hove Albion",
    "West Brom": "West Bromwich Albion",

    // La Liga (Spain)
    "Ath Bilbao": "Athletic Club",
    "Ath Madrid": "Atletico Madrid",
    "Barcelona": "Barcelona",
    "Betis": "Real Betis",
    "Celta": "Celta Vigo",
    "Espanol": "Espanyol",
    "Real Madrid": "Real Madrid",
    "Sevilla": "Sevilla",
    "Sociedad": "Real Sociedad",
    "Valencia": "Valencia",
    "Valladolid": "Real Valladolid",
    "Villarreal": "Villarreal",

    // Serie A (Italy)
    "Inter": "Inter",
    "Milan": "AC Milan",
    "Juventus": "Juventus",
    "Napoli": "Napoli",
    "Roma": "Roma",
    "Lazio": "Lazio",
    "Atalanta": "Atalanta",
    "Fiorentina": "Fiorentina",

    // Bundesliga (Germany)
    "Bayern Munich": "Bayern Munich",
    "Dortmund": "Borussia Dortmund",
    "Leverkusen": "Bayer Leverkusen",
    "RB Leipzig": "RB Leipzig",
    "M'gladbach": "Borussia Monchengladbach",
    "Frankfurt": "Eintracht Frankfurt",

    // Ligue 1 (France)
    "Paris SG": "Paris Saint-Germain",
    "Marseille": "Marseille",
    "Lyon": "Lyon",
    "Monaco": "Monaco",
    "Lille": "Lille"
};

function normalizeTeamName(name) {
    if (!name) return "";
    const trimmed = name.trim();
    return teamMapping[trimmed] || trimmed;
}

// Main Processing Function
function processAllLeagues() {
    // 1. Get all CSV files
    if (!fs.existsSync(DATA_DIR)) {
        console.error(`❌ Error: Data directory not found at ${DATA_DIR}`);
        return;
    }

    const files = fs.readdirSync(DATA_DIR).filter(file => file.endsWith('.csv'));
    console.log(`found ${files.length} CSV files to process...`);

    let allOdds = {};
    let totalMatches = 0;

    // 2. Process each file
    files.forEach(file => {
        console.log(`Processing ${file}...`);
        const content = fs.readFileSync(path.join(DATA_DIR, file), 'utf8');
        const rows = content.split('\n');

        if (rows.length < 2) return;

        const headers = rows[0].split(',');

        // Find columns dynamically
        const homeIdx = headers.findIndex(h => h.trim() === 'HomeTeam');
        const awayIdx = headers.findIndex(h => h.trim() === 'AwayTeam');
        const dateIdx = headers.findIndex(h => h.trim() === 'Date');

        // Odds columns (Bet365 usually)
        const hOddsIdx = headers.findIndex(h => h.trim() === 'B365H' || h.trim() === 'AvgH');
        const dOddsIdx = headers.findIndex(h => h.trim() === 'B365D' || h.trim() === 'AvgD');
        const aOddsIdx = headers.findIndex(h => h.trim() === 'B365A' || h.trim() === 'AvgA');

        if (homeIdx === -1 || awayIdx === -1) {
            console.warn(`⚠️ Skipping ${file}: Could not find HomeTeam/AwayTeam columns`);
            return;
        }

        // Parse rows
        for (let i = 1; i < rows.length; i++) {
            const row = rows[i].split(',');
            if (row.length < 5) continue;

            const home = normalizeTeamName(row[homeIdx]);
            const away = normalizeTeamName(row[awayIdx]);

            if (!home || !away) continue;

            const key = `${home} vs ${away}`;

            // Only add if we have odds
            if (row[hOddsIdx] && row[dOddsIdx] && row[aOddsIdx]) {
                allOdds[key] = {
                    home: parseFloat(row[hOddsIdx]),
                    draw: parseFloat(row[dOddsIdx]),
                    away: parseFloat(row[aOddsIdx]),
                    date: row[dateIdx]
                };
                totalMatches++;
            }
        }
    });

    // 3. Save as a JavaScript file (Global Variable)
    // This allows it to be loaded locally without fetch() restrictions
    const jsContent = `// Auto-generated by process_odds.js
// Contains historical odds for ${totalMatches} matches
window.HISTORICAL_ODDS = ${JSON.stringify(allOdds, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, jsContent);
    console.log(`✅ Success! Processed ${totalMatches} matches.`);
    console.log(`Saved to: ${OUTPUT_FILE}`);
}

processAllLeagues();
